# Generated by Django 4.2.3 on 2023-07-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=10, verbose_name='DNI/C.E/PASAPORTE')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('sctr', models.CharField(max_length=50, verbose_name='SCTR salud y Pension')),
            ],
            options={
                'verbose_name': 'Trabajadores',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15, verbose_name='Marca del Vehiculo')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo vel Vehiculo')),
                ('placa', models.CharField(max_length=6, verbose_name='Placa de rodaje')),
                ('fv_soat', models.DateField(auto_now=True, verbose_name='SOAT-Fecha de Vencimiento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehiculos',
                'ordering': ['id'],
            },
        ),
    ]
