# Generated by Django 4.2.3 on 2023-09-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitas',
            options={'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.parqueo', verbose_name='Parqueo'),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='strc',
            field=models.FileField(upload_to='strc/', verbose_name='STRC'),
        ),
    ]
