# Generated by Django 4.2.3 on 2023-10-03 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='salas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salas',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.puesto', verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='salas',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.puesto', verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.parqueo', verbose_name='Parqueo'),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.visitas', verbose_name='Visita'),
        ),
        migrations.AddField(
            model_name='asignacionev',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='asignacionepps',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
    ]
