# Generated by Django 4.2.3 on 2023-07-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEPPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casco', models.BooleanField(default=False, verbose_name='Casco')),
                ('barbiquejo', models.BooleanField(default=False, verbose_name='Barbiquejo')),
                ('botas', models.BooleanField(default=False, verbose_name='Botas punta de acero')),
                ('tapones', models.BooleanField(default=False, verbose_name='Tapones de oido')),
                ('lentes', models.BooleanField(default=False, verbose_name='Lentes de seguridad')),
                ('chaleco', models.BooleanField(default=False, verbose_name='Chaleco reflectivo')),
                ('respirador', models.BooleanField(default=False, verbose_name='Respirador doble via')),
            ],
            options={
                'verbose_name': 'AsingacionEPPS',
                'verbose_name_plural': 'AsignacionEPPS',
                'db_table': 'asignacion_epps',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botiquin', models.BooleanField(default=False, verbose_name='Botiquin')),
                ('extintor', models.BooleanField(default=False, verbose_name='Extintor')),
                ('trinagulo_s', models.BooleanField(default=False, verbose_name='Triangulo de Seguridad')),
                ('cono_s', models.BooleanField(default=False, verbose_name='Cono de seguridad')),
                ('taco', models.BooleanField(default=False, verbose_name='taco')),
            ],
            options={
                'verbose_name': 'AsignacionEVS',
                'db_table': 'asignacion_ev',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(default='', max_length=15, verbose_name='Marca del Vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='modelo',
            field=models.CharField(default='', max_length=20, verbose_name='Modelo vel Vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='placa',
            field=models.CharField(default='', max_length=6, verbose_name='Placa de rodaje'),
        ),
    ]
