# Generated by Django 4.2.3 on 2023-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosalida',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='h_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='h_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
