# Generated by Django 4.2.3 on 2023-07-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_asignacionepps_asignacionev_alter_vehiculos_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_procedencia', models.CharField(max_length=100, verbose_name='Empresa de procedencia')),
                ('p_visita', models.CharField(max_length=150, verbose_name='Persona a la que visiata')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo de la visita')),
                ('p_autoriza', models.CharField(max_length=50, verbose_name='persona que autoriza')),
                ('n_pase', models.CharField(max_length=10, verbose_name='Numero de pase')),
                ('n_parqueo', models.CharField(max_length=10, verbose_name='Numero de parqueo')),
                ('sala', models.CharField(max_length=10, verbose_name='Asignacion de sala')),
                ('e_declarados', models.CharField(max_length=500, verbose_name='Equipos declarados')),
                ('hora_entrada', models.DateTimeField(auto_now=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.DateTimeField(auto_now=True, verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name': 'IngresoSalida',
                'verbose_name_plural': 'IngresosSalidas',
                'db_table': 'ingresos_salidas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, verbose_name='Numero de Parqueo')),
            ],
            options={
                'verbose_name': 'Parqueo',
                'verbose_name_plural': 'Parqueos',
                'db_table': 'parqueos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=10, verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'salas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('h_inicio', models.TimeField(auto_now=True, verbose_name='Hora de inicio')),
                ('h_termino', models.TimeField(auto_now=True, verbose_name='Hora de termino')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.salas')),
                ('visitado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.trabajadores')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visitas',
                'ordering': ['id'],
            },
        ),
    ]
