# Generated by Django 4.2.3 on 2023-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_visitas_options_alter_asistentes_n_parqueo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentes',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
    ]
