# Generated by Django 4.2.3 on 2023-10-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_visitas_h_llegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistentes',
            name='strc',
        ),
        migrations.AddField(
            model_name='asistentes',
            name='sctr',
            field=models.FileField(blank=True, null=True, upload_to='strc/', verbose_name='STRC'),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='marca_v',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca del vehiculo'),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='modelo_v',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo del vehiculo'),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='placa_v',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa del vehiculo'),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='soat_v',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='FV-SOAT'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='sala',
            field=models.CharField(max_length=100, unique=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'PROGRAMADO'), ('2', 'EN CURSO'), ('3', 'FINALIZO')], max_length=10, null=True),
        ),
    ]
