# Generated by Django 4.2.3 on 2023-09-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_ingresosalida_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionev',
            name='circulina',
            field=models.BooleanField(default=False, verbose_name='Circulina'),
        ),
        migrations.AddField(
            model_name='asignacionev',
            name='pertiga',
            field=models.BooleanField(default=False, verbose_name='pertiga'),
        ),
    ]
