# Generated by Django 4.2.3 on 2023-07-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_ingresosalida_parque_salas_visitas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parque',
            new_name='Parqueo',
        ),
        migrations.AddField(
            model_name='visitas',
            name='fv_soat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SOAT-VEHICULO'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.parqueo', verbose_name='Numero de Parqueo'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='strc_salud',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SOAT-F.V.'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='v_marca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca del Vehiculo'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='v_modelo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo del vehiculo'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='v_placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa de rodaje'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='h_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='h_termino',
            field=models.TimeField(verbose_name='Hora de termino'),
        ),
    ]
