# Generated by Django 4.2.3 on 2023-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_asistentes_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='soat_v',
            field=models.DateField(verbose_name='FV-SOAT'),
        ),
    ]
