# Generated by Django 4.2.3 on 2023-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_rename_parque_parqueo_visitas_fv_soat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='estado',
            field=models.CharField(blank=True, choices=[('PROGRAMADA', '1'), ('ENTRADA', '2')], max_length=10, null=True),
        ),
    ]
