# Generated by Django 4.2.3 on 2023-09-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_empresa_user_unidad_alter_unidad_empresa_and_more'),
        ('erp', '0004_asignacionev_circulina_asignacionev_pertiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.puesto', verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='salas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salas',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.puesto', verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='salas',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='unidad'),
        ),
    ]
