# Generated by Django 4.2.3 on 2023-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_asistentes_soat_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='soat_v',
            field=models.DateField(default='14-09-2023', verbose_name='FV-SOAT'),
        ),
    ]
