# Generated by Django 4.2.3 on 2023-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_asistentes_strc_asistentes_sctr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueo',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='Numero de Parqueo'),
        ),
    ]
