# Generated by Django 4.2.3 on 2023-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_parqueo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='h_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='h_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Finalizacion'),
        ),
    ]
