# Generated by Django 4.2.3 on 2023-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_visitas_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitas',
            name='visitado',
        ),
        migrations.AlterField(
            model_name='visitas',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'PROGRAMADA'), ('2', 'ENTRADA')], max_length=10, null=True),
        ),
    ]
