# Generated by Django 4.2.3 on 2023-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_parqueo_empresa_parqueo_puesto_parqueo_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='sctr',
            field=models.FileField(upload_to='sctr/', verbose_name='SCTR salud y Pension'),
        ),
    ]
