# Generated by Django 4.2.3 on 2023-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_remove_visitas_visitado_alter_visitas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='h_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de termino'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='strc_salud',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='STRC-SALUD'),
        ),
    ]
