# Generated by Django 4.2.3 on 2023-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_trabajadores_sctr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='sctr',
            field=models.FileField(blank=True, null=True, upload_to='sctr/', verbose_name='SCTR'),
        ),
    ]
