# Generated by Django 4.2.3 on 2023-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_visitas_h_termino_alter_visitas_strc_salud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueo',
            name='numero',
            field=models.CharField(max_length=5, unique=True, verbose_name='Numero de Parqueo'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='sala',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
    ]
