# Generated by Django 4.2.3 on 2023-10-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_visitas_p_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='direccion',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=9, null=True, verbose_name='Celular'),
        ),
    ]
