# Generated by Django 4.2.3 on 2023-10-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_trabajadores_direccion_trabajadores_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
    ]
