# Generated by Django 4.2.3 on 2023-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_parqueo_numero_alter_salas_sala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='salas',
            name='estado',
            field=models.IntegerField(default=0, max_length=1, verbose_name='Estado'),
        ),
    ]
