# Generated by Django 4.2.3 on 2023-10-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_trabajadores_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
    ]
