# Generated by Django 4.2.3 on 2023-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_parqueo_estado_salas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueo',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='estado',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Estado'),
        ),
    ]
