# Generated by Django 4.2.3 on 2023-10-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_salas_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueo',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del parqueo'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fv_soat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de vencimiento del SOAT'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='p_visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.trabajadores', verbose_name='Persona a quien visita'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='tipo',
            field=models.CharField(choices=[('1', 'VISITA'), ('2', 'COURRIER/DELIVERY')], default='1', max_length=3),
        ),
    ]
