# Generated by Django 4.2.3 on 2023-08-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_parqueo_estado_alter_salas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'PROGRAMÓ'), ('2', 'ENTRÓ'), ('3', 'VISITÓ')], max_length=10, null=True),
        ),
    ]
