# Generated by Django 4.2.3 on 2023-08-04 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0011_alter_visitas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza'),
        ),
    ]
