# Generated by Django 4.2.3 on 2023-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_visitas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='tipo',
            field=models.CharField(choices=[('1', 'VISITA'), ('2', 'COURRIER'), ('3', 'DELIVERY')], default='1', max_length=3),
        ),
    ]
