# Generated by Django 4.2.3 on 2023-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_historicalvisitas_historicalvehiculos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisitas',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
    ]
