# Generated by Django 4.2.3 on 2023-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_visitas_observacion_visitas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='cantidad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='guias',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Guias de remision'),
        ),
    ]
