# Generated by Django 4.2.3 on 2023-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_historicalvisitas_nombre_alter_visitas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisitas',
            name='sctr_salud',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='SCTR-SALUD'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='sctr_salud',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='SCTR-SALUD'),
        ),
    ]
