# Generated by Django 4.2.3 on 2023-08-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_visitas_cantidad_visitas_guias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='guias',
            field=models.FileField(blank=True, null=True, upload_to='archivos/guias/', verbose_name='Guias de remision'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.salas'),
        ),
    ]
