# Generated by Django 4.2.3 on 2023-10-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_historicalvisitas_sctr_salud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitas',
            name='documentos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='documentos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Documentos'),
        ),
    ]
