# Generated by Django 4.2.3 on 2023-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_alter_visitas_guias_alter_visitas_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionev',
            old_name='trinagulo_s',
            new_name='triangulo_s',
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'DNI'), ('2', 'C.E'), ('3', 'PASAPORTE')], max_length=3, null=True),
        ),
    ]
