# Generated by Django 4.2.3 on 2023-10-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_historicalvisitas_documentos_visitas_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingresosalida',
            name='tipo',
            field=models.CharField(choices=[(1, 'INGRESO'), (2, 'SALIDA')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='tipo',
            field=models.CharField(choices=[(1, 'INGRESO'), (2, 'SALIDA')], default=2, max_length=15),
            preserve_default=False,
        ),
    ]
