# Generated by Django 4.2.3 on 2023-08-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_rename_trinagulo_s_asignacionev_triangulo_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionepps',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='asignacionev',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='documento',
            field=models.CharField(max_length=10, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
    ]
