# Generated by Django 4.2.3 on 2023-10-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_historicalingresosalida_tipo_ingresosalida_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingresosalida',
            old_name='h_salida',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='ingresosalida',
            old_name='h_salida',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='historicalingresosalida',
            name='h_entrada',
        ),
        migrations.RemoveField(
            model_name='ingresosalida',
            name='h_entrada',
        ),
    ]
