# Generated by Django 4.2.3 on 2023-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_asignacionepps_trabajador_asignacionev_trabajador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
