# Generated by Django 4.2.3 on 2023-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_rename_h_salida_historicalingresosalida_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingresosalida',
            name='motivo',
            field=models.CharField(default=1, max_length=200, verbose_name='Motivo del ingreso o salida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='motivo',
            field=models.CharField(default=2, max_length=200, verbose_name='Motivo del ingreso o salida'),
            preserve_default=False,
        ),
    ]
