# Generated by Django 4.2.3 on 2023-10-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_historicalingresosalida_motivo_ingresosalida_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingresosalida',
            name='fecha',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicalingresosalida',
            name='hora',
            field=models.TimeField(auto_created=True, blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='fecha',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='hora',
            field=models.TimeField(auto_created=True, blank=True, null=True, verbose_name='Hora de salida'),
        ),
    ]
