# Generated by Django 4.2.3 on 2023-11-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_historicalingresosalida_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionepps',
            options={'ordering': ['id'], 'verbose_name': 'AsignacionEPPS', 'verbose_name_plural': 'AsignacionEPPS'},
        ),
        migrations.AlterModelOptions(
            name='asistentes',
            options={'permissions': [('add_asinten', 'Puede agregar nuevos asistentes a una reunion'), ('view_asisten', 'Puede ver todos los asistentes de una reunion'), ('delete_asisten', 'Puede ver todos los asistentes de una reunion'), ('cahnge_asisten', 'Puede los datos de un asitente de la reunion')], 'verbose_name': 'asinten', 'verbose_name_plural': 'asistentes'},
        ),
        migrations.AlterModelOptions(
            name='historicalasignacionepps',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AsignacionEPPS', 'verbose_name_plural': 'historical AsignacionEPPS'},
        ),
    ]
