# Generated by Django 4.2.3 on 2023-11-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_asignacionepps_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Tcargo',
                'verbose_name_plural': 'Tcargos',
                'db_table': 'cargo_trabajador',
            },
        ),
        migrations.AlterModelOptions(
            name='asistentes',
            options={'verbose_name': 'asinten', 'verbose_name_plural': 'asistentes'},
        ),
        migrations.RenameField(
            model_name='historicalingresosalida',
            old_name='hora',
            new_name='hora_ingreso',
        ),
        migrations.RenameField(
            model_name='ingresosalida',
            old_name='hora',
            new_name='hora_ingreso',
        ),
        migrations.RemoveField(
            model_name='historicalingresosalida',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historicalingresosalida',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historicalingresosalida',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='historicalingresosalida',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ingresosalida',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='ingresosalida',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ingresosalida',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='ingresosalida',
            name='tipo',
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.parqueo', verbose_name='Numero de parqueo'),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa del vehiculo'),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='trabajador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='historicaltrabajadores',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.parqueo', verbose_name='Numero de parqueo'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa del vehiculo'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalingresosalida',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo del ingreso o salida'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo del ingreso o salida'),
        ),
        migrations.AddField(
            model_name='historicaltrabajadores',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.cargotrabajador', verbose_name='Cargo del trabajador'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.cargotrabajador', verbose_name='Cargo del trabajador'),
        ),
    ]
