# Generated by Django 4.2.3 on 2023-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_cargotrabajador_alter_asistentes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingresosalida',
            name='fecha',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
