# Generated by Django 4.2.3 on 2023-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_historicalingresosalida_fecha_ingresosalida_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargotrabajador',
            name='cargo',
            field=models.CharField(max_length=150, unique=True, verbose_name='Cargo'),
        ),
    ]
