# Generated by Django 4.2.3 on 2023-11-16 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0026_alter_historicalparqueo_estado_alter_parqueo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingresosalida',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='usuario',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
