# Generated by Django 4.2.3 on 2023-11-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_alter_historicalingresosalida_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosalida',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.trabajadores', verbose_name='Trabajador'),
            preserve_default=False,
        ),
    ]
