# Generated by Django 4.2.3 on 2023-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
