# Generated by Django 4.2.3 on 2023-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_empresa_remove_user_unidad_unidad_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'unidad', 'verbose_name_plural': 'unidades'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion'),
        ),
    ]
