# Generated by Django 4.2.3 on 2023-09-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_unidad_options_empresa_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='unidad',
            field=models.CharField(max_length=150, verbose_name='Ubicacion'),
        ),
    ]
