# Generated by Django 4.2.3 on 2023-09-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_empresa_user_unidad_alter_unidad_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='unidad',
            field=models.CharField(max_length=150, verbose_name='Unidad'),
        ),
    ]
